# Using NGINX to PROXY my app services
FROM nginx:alpine
# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf
# Expose port 80 for NGINX
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]