FROM fluent/fluentd:v1.12-debian-1
USER root
RUN gem install fluent-plugin-elasticsearch
USER fluent
COPY fluent.conf /fluentd/etc/

CMD [ "fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins" ]